import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

test("voxel chunk inventory preserves structural encoding evidence without chunk bodies", async () => {
  const text = await readFile(resolve(root, "evidence", "voxel-chunk-inventory.json"), "utf8");
  const evidence = JSON.parse(text);
  assert.equal(evidence.format, "nea-redacted-voxel-chunk-inventory");
  assert.equal(evidence.version, 1);
  assert.equal(evidence.privacy.sourceValuesIncluded, false);
  assert.equal(evidence.privacy.sourcePathsIncluded, false);
  assert.equal(evidence.privacy.sourceNamesIncluded, false);
  assert.equal(evidence.privacy.sourceChunkBodiesIncluded, false);
  assert.equal(evidence.provenance.publicStatus, "public-sanitized");
  assert.equal(evidence.conversionReadiness.targetFormat, "nea-terrain/v1");
  assert.equal(evidence.conversionReadiness.status, "evidence-blocked");
  assert.equal(evidence.conversionReadiness.playerArchiveDecoder.input, "archive asset body");
  assert.equal(evidence.conversionReadiness.playerArchiveDecoder.status, "confirmed-observed");
  assert.match(evidence.conversionReadiness.playerArchiveDecoder.reason, /archive body decoder/i);
  assert.deepEqual(evidence.samples.map(sample => sample.sample), ["sample-001"]);
  const sample = evidence.samples[0];
  assert.deepEqual(sample.shape.axes, ["x", "y", "z"]);
  assert.equal(sample.chunks.type, "array");
  assert.equal(sample.chunks.itemType, "string");
  assert.equal(sample.chunks.encoding, "base64url");
  assert.equal(sample.chunks.jsonEncoded, false);
  assert.equal(sample.chunks.encodedLength.min, sample.chunks.encodedLength.max);
  assert.equal(sample.chunks.decodedLength.min, sample.chunks.decodedLength.max);
  assert.equal(sample.resolver.status, "confirmed-observed");
  assert.equal(sample.resolver.resolvedEntries, 41);
  assert.equal(sample.resolver.response.entryLocation, "terminal-url-path");
  assert.equal(sample.resolver.decoder.status, "confirmed-observed");
  assert.equal(sample.resolver.decoder.decodedEntries + sample.resolver.decoder.failedEntries, sample.resolver.resolvedEntries);
  assert.equal(sample.resolver.decoder.decodedEntries, 41);
  assert.equal(sample.resolver.decoder.failedEntries, 0);
  assert.equal(Object.values(sample.resolver.decoder.errorCategories).reduce((total, count) => total + count, 0), 0);
  assert.ok(Object.keys(sample.resolver.decoder.errorCategories).every(category => /^[a-z-]+$/.test(category)));
  assert.equal(sample.resolver.decoder.limits.chunkSize, 32);
  assert.equal(sample.resolver.decoder.limits.paletteEntries, 4096);
  assert.equal(sample.resolver.decoder.limits.boxes, 32768);
  assert.ok(sample.resolver.decoder.paletteEntries.max <= sample.resolver.decoder.limits.paletteEntries);
  assert.ok(sample.resolver.decoder.boxes.max <= sample.resolver.decoder.limits.boxes);
  assert.ok(sample.resolver.decoder.boxes.total > 0);
  assert.ok(sample.resolver.decoder.blockIds.min >= 0);
  assert.doesNotMatch(text, /works\/private|manual-cdp|bedwars|parkour|[A-Za-z0-9_-]{40,}/i);
});
